# Generated by Django 4.1.2 on 2022-11-05 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lenta', '0003_postimage_delete_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
