# Generated by Django 4.1.2 on 2022-11-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenta', '0005_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(height_field=228, upload_to='post_pics', verbose_name='image', width_field=228),
        ),
    ]
