# Generated by Django 4.1.3 on 2022-11-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenta', '0007_alter_postimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_pics', verbose_name='image'),
        ),
    ]
