# Generated by Django 4.1.3 on 2022-11-23 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lenta', '0008_alter_postimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='lenta_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
