# Generated by Django 4.1.3 on 2022-12-14 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lenta', '0009_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='seen',
            field=models.ManyToManyField(related_name='lenta_posts_seen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='lenta_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
