# Generated by Django 4.1.3 on 2022-12-20 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lenta', '0010_post_seen_alter_post_likes'),
    ]

    operations = [
        migrations.RunSQL('ALTER SEQUENCE lenta_postimage_id_sec RESTART WITH 14764;'),
        migrations.RunSQL('ALTER SEQUENCE lenta_post_id_seq RESTART WITH 9207;')

    ]
