# Generated by Django 4.1.3 on 2022-12-20 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lenta', '0011_auto_20221221_0105'),
    ]

    operations = [
        migrations.RunSQL('ALTER SEQUENCE lenta_postimage_id_seq RESTART WITH 14764;'),
        migrations.RunSQL('ALTER SEQUENCE lenta_post_id_seq RESTART WITH 9207;')
    ]
