# Generated by Django 4.1.3 on 2022-12-20 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20221221_0112'),
    ]

    operations = [
    ]
