version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "lenta"
      POSTGRES_USER: "lenta"
      POSTGRES_PASSWORD: "lenta"
    restart: always
    ports:
      - "5431:5432/tcp"
      - "5431:5432/udp"
    
    volumes: 
      - ./pgdata1:/var/lib/postgresql/data

volumes:
  pgdata1:



